/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.mydemik.com;

import entiti.mydemik.com.Dosen;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import util.mydemik.com.HibernateUtil;

/**
 *
 * @author jajangtea
 */
public class __ListDosen extends javax.swing.JFrame {

    /**
     * Creates new form __ListDosen
     */
    Vector<String> tableHeaders = new Vector<String>();
    Vector tableData = new Vector();
    Query q;
    public __ListDosen() {
        initComponents();
        fillTable(TDosen);
    }
    
    private void fillTable(final JTable table) 
    {
        try
        {
            SessionFactory sf=HibernateUtil.getSessionFactory();
            Session s=sf.openSession();
            Transaction tx = s.beginTransaction();        
            try 
            {
                String sqlNIm="FROM Dosen where idDosen=:idDosen";
                String sqlAll="FROM Dosen";
                if(txtKodeDosen.getText().equals(""))
                {
                    q= s.createQuery(sqlAll);
                    jButton1.setText("Cari");
                }
                else
                {
                    q= s.createQuery(sqlNIm);
                    q.setParameter("idDosen", Integer.parseInt(txtKodeDosen.getText()));
                    jButton1.setText("Refresh");
                    txtKodeDosen.setText("");
                }
                List resultList = q.list();
                tableHeaders.removeAllElements();
                tableHeaders.add("Kode Dosen");
                tableHeaders.add("Nama");
                tableHeaders.add("Handphone");
                tableData.removeAllElements();
                for(Object o : resultList) 
                {
                    Dosen sr = (Dosen)o;
                    Vector<Object> oneRow = new Vector<Object>();
                    oneRow.add(sr.getKodeDosen());
                    oneRow.add(sr.getNamaDosen().toString());
                    oneRow.add(sr.getHp().toString());
                    tableData.add(oneRow);
                }
                TDosen.setModel(new DefaultTableModel(tableData, tableHeaders));
                s.flush();
                tx.commit();
                s.close();
            } catch (Exception e) 
            {
                System.out.println(e);
            }
            
        }
        catch (ClassCastException e) 
        {
                System.out.println("Another error "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TDosen = new javax.swing.JTable();
        txtKodeDosen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pencarian Mahasiswa");

        TDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TDosen);

        txtKodeDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeDosenActionPerformed(evt);
            }
        });
        txtKodeDosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKodeDosenKeyTyped(evt);
            }
        });

        jLabel1.setText("NIM/Nama :");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKodeDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambah)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeDosenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeDosenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeDosenKeyTyped

    private void txtKodeDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeDosenActionPerformed
        // TODO add your handling code here:
        fillTable(TDosen);
    }//GEN-LAST:event_txtKodeDosenActionPerformed

    private void TDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TDosenMouseClicked
        // TODO add your handling code here:
        int baris =TDosen.getSelectedRow();
        __EntryJadwal fs;
        try {
            fs = new __EntryJadwal();
            fs.txtKodeDosen.setText(TDosen.getValueAt(baris,0).toString());
            fs.cari(fs.txtKodeDosen.getText());
            this.setVisible(false);
            fs.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(__ListDosen.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_TDosenMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillTable(TDosen);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(__ListDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(__ListDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(__ListDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(__ListDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new __ListDosen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TDosen;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtKodeDosen;
    // End of variables declaration//GEN-END:variables
}
