package entiti.mydemik.com;
// Generated May 3, 2017 9:29:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private Integer idDosen;
     private String kodeDosen;
     private String namaDosen;
     private String hp;
     private Set jadwals = new HashSet(0);

    public Dosen() {
    }

    public Dosen(String kodeDosen, String namaDosen, String hp, Set jadwals) {
       this.kodeDosen = kodeDosen;
       this.namaDosen = namaDosen;
       this.hp = hp;
       this.jadwals = jadwals;
    }
   
    public Integer getIdDosen() {
        return this.idDosen;
    }
    
    public void setIdDosen(Integer idDosen) {
        this.idDosen = idDosen;
    }
    public String getKodeDosen() {
        return this.kodeDosen;
    }
    
    public void setKodeDosen(String kodeDosen) {
        this.kodeDosen = kodeDosen;
    }
    public String getNamaDosen() {
        return this.namaDosen;
    }
    
    public void setNamaDosen(String namaDosen) {
        this.namaDosen = namaDosen;
    }
    public String getHp() {
        return this.hp;
    }
    
    public void setHp(String hp) {
        this.hp = hp;
    }
    public Set getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set jadwals) {
        this.jadwals = jadwals;
    }




}


