package entiti.mydemik.com;
// Generated May 3, 2017 9:29:35 AM by Hibernate Tools 4.3.1



/**
 * Jadwalmhs generated by hbm2java
 */
public class Jadwalmhs  implements java.io.Serializable {


     private Integer idJadwalMhs;
     private Jadwal jadwal;
     private Mahasiswa mahasiswa;

    public Jadwalmhs() {
    }

    public Jadwalmhs(Jadwal jadwal, Mahasiswa mahasiswa) {
       this.jadwal = jadwal;
       this.mahasiswa = mahasiswa;
    }
   
    public Integer getIdJadwalMhs() {
        return this.idJadwalMhs;
    }
    
    public void setIdJadwalMhs(Integer idJadwalMhs) {
        this.idJadwalMhs = idJadwalMhs;
    }
    public Jadwal getJadwal() {
        return this.jadwal;
    }
    
    public void setJadwal(Jadwal jadwal) {
        this.jadwal = jadwal;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }




}


