package entiti.mydemik.com;
// Generated May 3, 2017 9:29:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jadwal generated by hbm2java
 */
public class Jadwal  implements java.io.Serializable {


     private Integer idJadwal;
     private Dosen dosen;
     private Jenisujian jenisujian;
     private Matkul matkul;
     private Ruangan ruangan;
     private Thajaran thajaran;
     private Date tanggal;
     private String jam;
     private Set jadwalmhses = new HashSet(0);

    public Jadwal() {
    }

    public Jadwal(Dosen dosen, Jenisujian jenisujian, Matkul matkul, Ruangan ruangan, Thajaran thajaran, Date tanggal, String jam, Set jadwalmhses) {
       this.dosen = dosen;
       this.jenisujian = jenisujian;
       this.matkul = matkul;
       this.ruangan = ruangan;
       this.thajaran = thajaran;
       this.tanggal = tanggal;
       this.jam = jam;
       this.jadwalmhses = jadwalmhses;
    }
   
    public Integer getIdJadwal() {
        return this.idJadwal;
    }
    
    public void setIdJadwal(Integer idJadwal) {
        this.idJadwal = idJadwal;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Jenisujian getJenisujian() {
        return this.jenisujian;
    }
    
    public void setJenisujian(Jenisujian jenisujian) {
        this.jenisujian = jenisujian;
    }
    public Matkul getMatkul() {
        return this.matkul;
    }
    
    public void setMatkul(Matkul matkul) {
        this.matkul = matkul;
    }
    public Ruangan getRuangan() {
        return this.ruangan;
    }
    
    public void setRuangan(Ruangan ruangan) {
        this.ruangan = ruangan;
    }
    public Thajaran getThajaran() {
        return this.thajaran;
    }
    
    public void setThajaran(Thajaran thajaran) {
        this.thajaran = thajaran;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getJam() {
        return this.jam;
    }
    
    public void setJam(String jam) {
        this.jam = jam;
    }
    public Set getJadwalmhses() {
        return this.jadwalmhses;
    }
    
    public void setJadwalmhses(Set jadwalmhses) {
        this.jadwalmhses = jadwalmhses;
    }

    @Override
    public String toString() {
        return jam;
    }




}


