package entiti.mydemik.com;
// Generated May 3, 2017 9:29:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private Integer idMahasiswa;
     private Prodi prodi;
     private int nim;
     private String nama;
     private String alamat;
     private String tlp;
     private Set surats = new HashSet(0);
     private Set jadwalmhses = new HashSet(0);

    public Mahasiswa() {
    }

	
    public Mahasiswa(Prodi prodi, int nim, String nama, String alamat, String tlp) {
        this.prodi = prodi;
        this.nim = nim;
        this.nama = nama;
        this.alamat = alamat;
        this.tlp = tlp;
    }
    public Mahasiswa(Prodi prodi, int nim, String nama, String alamat, String tlp, Set surats, Set jadwalmhses) {
       this.prodi = prodi;
       this.nim = nim;
       this.nama = nama;
       this.alamat = alamat;
       this.tlp = tlp;
       this.surats = surats;
       this.jadwalmhses = jadwalmhses;
    }
   
    public Integer getIdMahasiswa() {
        return this.idMahasiswa;
    }
    
    public void setIdMahasiswa(Integer idMahasiswa) {
        this.idMahasiswa = idMahasiswa;
    }
    public Prodi getProdi() {
        return this.prodi;
    }
    
    public void setProdi(Prodi prodi) {
        this.prodi = prodi;
    }
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getTlp() {
        return this.tlp;
    }
    
    public void setTlp(String tlp) {
        this.tlp = tlp;
    }
    public Set getSurats() {
        return this.surats;
    }
    
    public void setSurats(Set surats) {
        this.surats = surats;
    }
    public Set getJadwalmhses() {
        return this.jadwalmhses;
    }
    
    public void setJadwalmhses(Set jadwalmhses) {
        this.jadwalmhses = jadwalmhses;
    }




}


