package entiti.mydemik.com;
// Generated May 3, 2017 9:29:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Matkul generated by hbm2java
 */
public class Matkul  implements java.io.Serializable {


     private Integer idMatkul;
     private String kodeMatkul;
     private String namaMatkul;
     private Integer sks;
     private Set jadwals = new HashSet(0);

    public Matkul() {
    }

    public Matkul(String kodeMatkul, String namaMatkul, Integer sks, Set jadwals) {
       this.kodeMatkul = kodeMatkul;
       this.namaMatkul = namaMatkul;
       this.sks = sks;
       this.jadwals = jadwals;
    }
   
    public Integer getIdMatkul() {
        return this.idMatkul;
    }
    
    public void setIdMatkul(Integer idMatkul) {
        this.idMatkul = idMatkul;
    }
    public String getKodeMatkul() {
        return this.kodeMatkul;
    }
    
    public void setKodeMatkul(String kodeMatkul) {
        this.kodeMatkul = kodeMatkul;
    }
    public String getNamaMatkul() {
        return this.namaMatkul;
    }
    
    public void setNamaMatkul(String namaMatkul) {
        this.namaMatkul = namaMatkul;
    }
    public Integer getSks() {
        return this.sks;
    }
    
    public void setSks(Integer sks) {
        this.sks = sks;
    }
    public Set getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set jadwals) {
        this.jadwals = jadwals;
    }

    @Override
    public String toString() {
        return namaMatkul;
    }




}


