package entiti.mydemik.com;
// Generated May 3, 2017 9:29:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ruangan generated by hbm2java
 */
public class Ruangan  implements java.io.Serializable {


     private Integer idRuangan;
     private String noRuang;
     private Set jadwals = new HashSet(0);

    public Ruangan() {
    }

    public Ruangan(String noRuang, Set jadwals) {
       this.noRuang = noRuang;
       this.jadwals = jadwals;
    }
   
    public Integer getIdRuangan() {
        return this.idRuangan;
    }
    
    public void setIdRuangan(Integer idRuangan) {
        this.idRuangan = idRuangan;
    }
    public String getNoRuang() {
        return this.noRuang;
    }
    
    public void setNoRuang(String noRuang) {
        this.noRuang = noRuang;
    }
    public Set getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set jadwals) {
        this.jadwals = jadwals;
    }

    @Override
    public String toString() {
        return noRuang;
    }
    




}


